# Generated by Django 6.0.1 on 2026-02-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("cover_url", models.CharField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("duration", models.CharField(blank=True, max_length=120)),
                ("price_from", models.PositiveIntegerField(blank=True, null=True)),
                ("bullets", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("category", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to="gradnja.category")),
            ],
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name="ID")),
                ("image_url", models.CharField(max_length=500)),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name="images", to="gradnja.project")),
            ],
        ),
    ]
