# Generated by Django 6.0.1 on 2026-02-07 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradnja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Naziv')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorije',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Naslov')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Kratak opis')),
                ('description', models.TextField(blank=True, verbose_name='Detaljan opis')),
                ('bullets', models.TextField(blank=True, help_text='Svaki red = jedna stavka (bullet).', verbose_name='Šta je rađeno')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lokacija')),
                ('duration', models.CharField(blank=True, max_length=120, verbose_name='Trajanje')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena od (RSD)')),
                ('cover_url', models.URLField(blank=True, verbose_name='Naslovna slika (URL ili /static/... putanja)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Izdvojeno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='gradnja.category', verbose_name='Kategorija')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Slika (URL ili /static/... putanja)')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Opis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Redosled')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gradnja.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Upit',
        ),
    ]
